name: GitHubApiClient
targets:
  GitHubApiClient:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [GitHubApiClient]
    info:
      path: ./Info.plist
      version: 0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: Alamofire
